import test from 'node:test';import assert from 'node:assert/strict';
import {HomeControl,homeIntent,localHomeURL} from '../src/home-control';
test('room commands resolve named devices and brightness',()=>{assert.deepEqual(homeIntent('Hi Looma, turn on the desk lamp'),{name:'desk lamp',action:'on'});assert.deepEqual(homeIntent('dim desk lamp to 35%'),{name:'desk lamp',action:'on',brightness:35});assert.equal(homeIntent('dim lamp to 150%'),undefined);});
test('room access is local and never follows redirects with a token',()=>{assert.equal(localHomeURL('http://192.168.1.4:8123'),'http://192.168.1.4:8123');for(const u of ['https://example.com','http://10.evil.example','http://192.168.evil.example','http://user:pass@localhost','http://localhost/api/','http://localhost/?token=x'])assert.throws(()=>localHomeURL(u));});
test('mapped service calls contain only configured entity and bounded controls',async()=>{const requests:{url:string;init:RequestInit}[]=[];const room=new HomeControl({url:'http://127.0.0.1:8123',token:'private-test-token',enabled:true,bindings:[{name:'desk lamp',entity:'light.desk'}]},()=>{},(async(url:any,init:any)=>{requests.push({url,init});return new Response('[]',{status:200});}) as typeof fetch);
 assert(!JSON.stringify(room.status()).includes('private-test-token'));
 await room.execute({name:'desk lamp',action:'on',brightness:25});assert.equal(requests[0].url,'http://127.0.0.1:8123/api/services/light/turn_on');assert.equal(requests[0].init.redirect,'error');assert.deepEqual(JSON.parse(String(requests[0].init.body)),{entity_id:'light.desk',brightness_pct:25});await assert.rejects(()=>room.execute({name:'unconfigured lamp',action:'on'}));assert.equal(requests.length,1);
});
test('Broadlink uses learned commands and reports dispatch rather than claiming physical success',async()=>{let body:any;const room=new HomeControl({url:'http://localhost:8123',token:'test',enabled:true,bindings:[{name:'projector',entity:'remote.lounge',device:'projector',commandOn:'power_on',commandOff:'power_off'}]},()=>{},(async(_url:any,init:any)=>{body=JSON.parse(init.body);return new Response('[]');}) as typeof fetch);assert.match(await room.execute({name:'projector',action:'off'}),/^Sent/);assert.deepEqual(body,{entity_id:'remote.lounge',device:'projector',command:'power_off'});});

test('failed secure persistence does not activate a room configuration',()=>{const room=new HomeControl({},()=>{throw Error('storage unavailable')});assert.throws(()=>room.configure({url:'http://localhost:8123',token:'test',enabled:true}),/storage unavailable/);assert.equal(room.status().enabled,false);});

test('common turn typo routes locally and unconfigured room explains setup',async()=>{assert.deepEqual(homeIntent('trun on the tv'),{name:'tv',action:'on'});const room=new HomeControl({},()=>{});await assert.rejects(()=>room.execute({name:'tv',action:'on'}),/Smart room control is off/);});
