const {app,BrowserWindow,Menu}=require('electron');
const {mkdtempSync,rmSync,writeFileSync}=require('node:fs');
const {tmpdir}=require('node:os');
const {join}=require('node:path');
const assert=require('node:assert/strict');
const home=mkdtempSync(join(tmpdir(),'looma-ui-test-'));
app.setPath('userData',home);app.setAppPath(join(__dirname,'..'));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const deadline=setTimeout(()=>{console.error('UI test timed out');app.exit(1);},60000);
require('../dist/main.cjs');
app.whenReady().then(async()=>{try{
 let pet,workspace;
 for(let i=0;i<200;i++){
  const windows=BrowserWindow.getAllWindows();
  pet=windows.find(w=>w.getBounds().width===240);
  workspace=windows.find(w=>w.webContents.getURL().startsWith('http://127.0.0.1:'));
  if(workspace&&!workspace.webContents.isLoading())break;
  await wait(150);
 }
 assert(pet&&workspace,'Only the puppy and new workspace must start');
 assert.equal(BrowserWindow.getAllWindows().length,2);
 assert(BrowserWindow.getAllWindows().every(w=>!w.webContents.getURL().endsWith('/dist/index.html')),'Legacy dashboard must not exist');
 await wait(700);
 const evalPet=s=>pet.webContents.executeJavaScript(s),evalWeb=s=>workspace.webContents.executeJavaScript(s);
 assert.equal(await evalPet('document.querySelectorAll("button").length'),0);
 assert.equal(await evalPet('typeof require'),'undefined');
 assert.equal(await evalWeb(`Boolean(document.querySelector('[title="Toggle Desktop Screen Preview"]'))`),false);
 const settingsItem=Menu.getApplicationMenu().items[0].submenu.items.find(x=>x.label==='Settings');settingsItem.click();
 for(let i=0;i<40;i++){if(await evalWeb(`!!document.querySelector('[aria-label="Voice companion settings"]')`))break;await wait(100);}
 assert.match(await evalWeb('document.body.innerText'),/Talk to Looma/);
 assert.match(await evalWeb('document.body.innerText'),/Restart listening/);
 assert.match(await evalWeb('document.body.innerText'),/Smart room/);
 const room=await evalWeb(`fetch('/api/v1/desktop/home',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status'})}).then(r=>r.json())`);
 assert.equal(room.enabled,false);assert.equal(room.configured,false);assert(!('token' in room));
 const setupReply=await evalPet('window.careless.chat("Hi Looma, turn on desk lamp.")');
 assert.match(setupReply,/Smart room control is off/);assert(!setupReply.includes('external task'));
 const snapshot=await evalPet('window.careless.snapshot()');
 assert.equal(snapshot.settings.voiceInput,false);
 const response=await evalWeb(`fetch('/api/v1/desktop/companion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'settings',value:{microphoneId:'test-mic',wakeWord:false}})}).then(r=>r.status)`);
 assert.equal(response,200);
 await evalWeb(`fetch('/api/v1/desktop/companion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'settings',value:{voiceOutput:true}})})`);
 await evalWeb(`fetch('/api/v1/desktop/companion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'settings',value:{language:'ml'}})})`);
 assert.equal((await evalPet('window.careless.snapshot()')).settings.voiceOutput,true,'Changing language must not disable spoken replies');
 assert.equal((await evalPet('window.careless.snapshot()')).settings.microphoneId,'test-mic');
 assert.equal(await evalWeb(`fetch('/api/v1/desktop/companion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'settings',value:{arbitrary:true}})}).then(r=>r.status)`),400);
 await evalWeb(`fetch('/api/v1/desktop/companion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'settings',value:{voiceInput:true,wakeWord:false}})})`);
 await evalPet(`window.careless.voice({action:'remember',question:'Hi Looma',text:'Hello! I’m listening. What would you like to know?'})`);
 await evalWeb(`document.querySelector('[title="Close App Settings"]')?.click()`);
 for(let i=0;i<40;i++){if((await evalWeb('document.body.innerText')).includes('Hello! I’m listening.'))break;await wait(100);}
 assert.match(await evalWeb('document.body.innerText'),/Hello! I’m listening\./,'Voice greeting must appear without a focus change');
 await evalPet('window.careless.chat("Looma, sit down")');
 writeFileSync(join(__dirname,'../chat-demo-preview.png'),(await workspace.webContents.capturePage()).toPNG());
 await evalPet('window.careless.chat("Looma, chase the ball")');
 await wait(500);
 const ball=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/public/ball.html'));
 assert(ball,'Fetch creates a draggable desktop ball');
 const before=pet.getBounds();const area=require('electron').screen.getDisplayMatching(before).workArea;
 ball.setPosition(area.x+60,area.y+area.height-90);
 await wait(800);const after=pet.getBounds();assert.notEqual(after.x,before.x,'Puppy follows moved ball');
 await evalPet('window.careless.chat("Looma, stay")');await wait(150);assert(ball.isDestroyed(),'Stay removes ball');
 const idle=pet.getPosition();await wait(200);assert.deepEqual(pet.getPosition(),idle,'Stay stops desktop movement');
 const looks=Menu.getApplicationMenu().items[0].submenu.items.find(x=>x.label==='Puppy appearance').submenu.items;
 assert.equal(await evalPet('document.querySelector("#petCharacter svg")?.tagName'),'svg','Cartoon puppy is the default');
 looks.find(x=>x.label==='Animated 3D puppy').click();await wait(2500);
 assert.equal(await evalPet('document.querySelector(".puppy-3d")?.dataset.loaded === "true"'),true);
 assert.equal(await evalPet('document.querySelector(".puppy-3d")?.dataset.asset'), 'golden-0.3.9');
 assert(Number(await evalPet('document.querySelector(".puppy-3d")?.dataset.textures'))>=2,'Both the coat atlas and face detail must load');
 assert(Number(await evalPet('document.querySelector(".puppy-3d")?.dataset.skinnedMeshes'))>=2,'Body and fur must both be skinned');
 const frame=await pet.webContents.capturePage();assert.equal(frame.toBitmap()[3],0);
 writeFileSync(join(__dirname,'../pet-preview.png'),frame.toPNG());
 writeFileSync(join(__dirname,'../voice-settings-preview.png'),(await workspace.webContents.capturePage()).toPNG());
 looks.find(x=>x.label==='Original puppy picture').click();await wait(1200);assert.equal(await evalPet('!!document.querySelector(".puppy-portrait")'),true,'Original portrait remains available');
 looks.find(x=>x.label==='Animated 3D puppy').click();await wait(1200);assert.equal(await evalPet('document.querySelector(".puppy-3d")?.dataset.asset'),'golden-0.3.9','Switching back reuses the loaded 3D puppy');
 looks.find(x=>x.label==='Original cartoon puppy').click();await wait(1200);
 assert.equal(await evalPet('document.querySelector("#petCharacter svg")?.tagName'),'svg');
 writeFileSync(join(__dirname,'../cartoon-pet-preview.png'),(await pet.webContents.capturePage()).toPNG());
 workspace.hide();await evalPet('document.querySelector("#petCharacter").dispatchEvent(new MouseEvent("dblclick"))');await wait(200);assert(workspace.isVisible());
 console.log('PASS: new workspace only, no computer demo, voice controls, validated settings bridge, transparent puppy and double-click.');
 clearTimeout(deadline);app.quit();
}catch(e){console.error(e);clearTimeout(deadline);app.exit(1);}});
app.on('will-quit',()=>{try{rmSync(home,{recursive:true,force:true});}catch{}});
