'use client';
import {useEffect,useState} from 'react';
import {desktopService} from '../lib/api';
export default function AssistantControls(){
 const [items,setItems]=useState([]),[text,setText]=useState(''),[date,setDate]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const run=async value=>{setBusy(true);setError('');try{setItems(await desktopService('assistant',value));}catch(e){setError(e.message);}finally{setBusy(false);}};
 useEffect(()=>{desktopService('assistant',{action:'list'}).then(setItems).catch(e=>setError(e.message));},[]);
 return <section className="rounded-2xl border border-[#eadbc7] p-4 space-y-3"><h3 className="font-semibold">Apps, alarms & event announcements</h3><p className="text-xs">Looma must be running and your computer awake. Enable Speak replies to hear announcements. Missed reminders appear when Looma runs again.</p><div className="flex flex-wrap gap-2">{['browser','calculator','notes','calendar','music','files'].map(app=><button key={app} disabled={busy} onClick={()=>run({action:'open',app})} className="rounded-lg bg-[#eadbc7] p-2 text-sm">Open {app}</button>)}</div><form className="space-y-2" onSubmit={async e=>{e.preventDefault();await run({action:'alarm',text,due:new Date(date).getTime()});}}><input aria-label="Announcement" placeholder="Meeting, alarm, or reminder…" value={text} onChange={e=>setText(e.target.value)} className="w-full border rounded-lg p-2" required maxLength={500}/><input aria-label="Alarm date and time" type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} className="w-full border rounded-lg p-2" required/><button disabled={busy} className="rounded-lg bg-[#eadbc7] p-2">Set announcement</button></form>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{items.map(i=><div key={i.id} className="text-sm border-t pt-2"><p>{i.text}</p><p>{new Date(i.due).toLocaleString()}</p><button disabled={busy} onClick={()=>run({action:'cancel',id:i.id})}>Cancel</button></div>)}</section>;
}
