'use client';
import {useEffect,useState} from 'react';
import {desktopService} from '../lib/api';
export default function MediaStudio(){
 const [kind,setKind]=useState('image'),[prompt,setPrompt]=useState(''),[portrait,setPortrait]=useState(false),[jobs,setJobs]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;const load=async()=>{try{let list=await desktopService('media',{action:'list'});for(const j of list.filter(j=>j.status==='Generating'))list=await desktopService('media',{action:'poll',id:j.id});if(live)setJobs(list);}catch(e){if(live)setError(e.message);}};load();const timer=setInterval(load,5000);return()=>{live=false;clearInterval(timer);};},[]);
 const create=async e=>{e.preventDefault();setBusy(true);setError('');try{setJobs(await desktopService('media',{action:'create',kind,prompt,portrait}));setPrompt('');}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <section className="rounded-2xl border border-[#eadbc7] p-4 space-y-3"><h3 className="font-semibold">Create images & videos</h3><p className="text-xs">Uses your saved Google Gemini key. Google media access and billing are required. Only your description is sent.</p><form onSubmit={create} className="space-y-3"><select aria-label="Creation type" value={kind} onChange={e=>setKind(e.target.value)} className="border rounded-lg p-2 w-full"><option value="image">Image · Gemini</option><option value="video">8-second video · Veo</option></select><textarea aria-label="Describe your creation" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={3000} placeholder="Describe what you want to create…" className="border rounded-lg w-full p-2" required/>{kind==='video'&&<label className="flex gap-2"><input type="checkbox" checked={portrait} onChange={e=>setPortrait(e.target.checked)}/>Portrait for Reels</label>}<button disabled={busy||!prompt.trim()} className="rounded-lg bg-[#eadbc7] p-2 disabled:opacity-50">{busy?'Starting…':'Generate'}</button></form>{error&&<p role="alert" className="text-red-700 text-sm">{error}</p>}<div className="space-y-3">{jobs.map(j=><div key={j.id} className="border rounded-xl p-3"><p className="text-sm">{j.prompt}</p><p className="text-xs">{j.status}</p>{j.error&&<p className="text-sm text-red-700">{j.error}</p>}{j.url&&(j.kind==='image'?<img alt={j.prompt} src={j.url} className="w-full rounded-lg"/>:<video controls src={j.url} className="w-full rounded-lg"/>)}{j.url&&<a download href={j.url} className="block text-sm mt-2">Save {j.kind}</a>}</div>)}</div></section>;
}
